### ISSUE TITLE
adding simpel demo how to apply on a raster brick - with fast options from Github bfast2 - etc

### ISSUE THREAD

**Issue by janverbesselt** [verbe039/BFASTforAEO#12]
fast options activated - parallelisation? (towards landsat/sentinel2 processing)

**Comment by GreatEmerald** [comment]
It would be simple to add that, but that obviously makes it so that we need to install the GitHub version.

For #14 I implemented installing it via the `remotes` package, which is more lightweight than the `devtools` package. I could adapt the function for loading the packages to parse the input and if it detects a slash, to use `remotes::install_github()` for it.

**Comment by GreatEmerald** [comment]
Obsolete now that it's on CRAN, and also includes BFAST Lite on a raster brick via #15.
